language: node_js
"node_js":
  - "12"

cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn coverage

after_success:
  - yarn add coveralls
  - cat ./coverage/lcov.info | coveralls
